### ISSUE TITLE
Support for rename

### ISSUE THREAD

**Issue by dieend** [sonots/fluent-plugin-record-reformer#15]
It would be awesome if there is a feature to rename keys. With example configuration below, current implementation will add new record even if `old_name` not defined in record. It would be great if it's not creating `new_name` record if `old_name` not exists, or in other word, feature of renaming. 

```
<record>
   new_name ${old_name}
</record>
```

**Comment by sonots** [comment]
You can use `remove_keys` and `<record>` as:

```apache
<source>
  type dummy
  tag dummy
  dummy {"message":"foo"}
</source>

<match dummy>
  type record_reformer
  remove_keys message
  <record>
    foo ${message}
  </record>
  tag reformed.${tag}
</match>

<match reformed.**>
  type stdout
</match>
```

But, pull request is welcome! I am wondering for its good parameter interface, though.
