### ISSUE TITLE
field type?

### ISSUE THREAD

**Issue by glee0316** [sonots/fluent-plugin-record-reformer#16]
I am using timestamp ${time.strftime('%s')}, but it is saving it as a string...is there a way to tell record_reformer that the field is an integer?

Thanks!

**Comment by sonots** [comment]
record-reformer reforms as string, but you may be able to use https://github.com/tarom/fluent-plugin-typecast

**Comment by glee0316** [comment]
Thanks for the response...I am still new to all of this...

Can you give me an example of how typecast can be used in conjunction with
record-reformer?

Thanks!

**Comment by sonots** [comment]
Try this. You can see `foo` is casted to integer. 

```apache
<source>
  type dummy
  tag dummy
  dummy {"message":"foo"}
</source>

<match dummy>
  type record_reformer
  <record>
    foo 0
  </record>
  tag reformed.${tag}
</match>

<match reformed.**>
  type typecast
  item_types foo:integer
  prefix typed
</match>

<match typed.**>
  type stdout
</match>
```
