### ISSUE TITLE
Support integer type field with placeholder (including Ruby codes)

### ISSUE THREAD

**Issue by piroor** [sonots/fluent-plugin-record-reformer#23]
For example, there is a record like `{ "timestamp" => "2015-06-10T10:00:00" }` and I hope to convert it to an unitxime. Then the configuration will be:

```
enable_ruby true
<record>
  timestamp ${Time.parse(timestamp).to_i}
</record>
```

But it doesn't work as expected, because placeholders are always expanded as strings.

**Comment by piroor** [comment]
This is dup of #16. Sorry.

**Comment by sonots** [comment]
Yep, please use the typecast plugin, thanks.
