### ISSUE TITLE
json type not supported in ruby placeholder

### ISSUE THREAD

**Issue by pgodot** [sonots/fluent-plugin-record-reformer#35]
if I have:

     <match hubbleCamelRouteJmx>
       type record_reformer
       remove_keys request
       renew_record false
       enable_ruby true
       auto_typecast true
       tag reformedhubbleCamelRouteJmx
       <record>
         value "[{\"hubbleBean\" : { \"name\" : \"myBean1\", \"stat1\":0}}, {\"hubbleBean\" : { \"name\" : \"myBean2\", \"stat1\":0}}]"
    #    value ${JSON.parse('[{"hubbleBean" : { "name" : "myBean1", "stat1":0}}, {"hubbleBean" : { "name" : "myBean2", "stat1":0}}]')}
       </record>
     </match>

The first reformer is working well but if I used ruby placeholder record reformer will send a string instead of json.

Thanks,
Phil

**Comment by sonots** [comment]
JSON.parse creates ruby hash object, and your are seeing hash.to_s.

JSON.parse().to_json creates JSON string, but I think you don't need to do even JSON.parse

**Comment by pgodot** [comment]
Thanks Sonots for your response.
 I tried many combinaison:
${'[{"hubbleBean" : { "name" : "myBean1", "stat1":0}}, {"hubbleBean" : { "name" : "myBean2", "stat1":0}}]'}
${'[{"hubbleBean" : { "name" : "myBean1", "stat1":0}}, {"hubbleBean" : { "name" : "myBean2", "stat1":0}}]'.to_json}

I'm seeing hash.to_s but fluentd also because when you are trying to split the json array by unwind plugin it's not effective. It seems that unwind see a string and not split it.

**Comment by sonots** [comment]
Let me clarify. What you want to send is a hash? JSON text is a String, so I am confused.

**Comment by pgodot** [comment]
This record-reformer 
value "[{\"hubbleBean\" : { \"name\" : \"myBean1\", \"stat1\":0}}, {\"hubbleBean\" : { \"name\" : \"myBean2\", \"stat1\":0}}]"

will work for unwind (split it in 2 events). I 'm trying to find a way to do the same but dynamicly with a ruby placeholder with no success.

**Comment by sonots** [comment]
If you write as:

```
  <source>
    type dummy
    dummy {"foo":"bar"}
    tag hubbleCamelRouteJmx
  </source>
  <match hubbleCamelRouteJmx>
    type record_reformer
    remove_keys request
    renew_record false
    enable_ruby true
    auto_typecast true
    tag reformedhubbleCamelRouteJmx
    <record>
      value ${record}
    </record>
  </match>
  <match reformedhubbleCamelRouteJmx>
    type stdout
  </match>
```

You can get

```
2016-03-01 23:50:38 +0900 reformedhubbleCamelRouteJmx: {"foo":"bar","value":{"foo":"bar"}}
2016-03-01 23:50:39 +0900 reformedhubbleCamelRouteJmx: {"foo":"bar","value":{"foo":"bar"}}
```

Is this what you want to do?

**Comment by pgodot** [comment]
Oki it's working. but what about if we want to change the record. By example:
<system>
log_level info
</system>
<source>
type dummy
dummy {"foo":"bar", "hello" : "me", "value" : {"myobject" : {"name" : "object1"}}}
tag hubbleCamelRouteJmx
</source>
<match hubbleCamelRouteJmx>
type record_reformer
remove_keys request
renew_record false
enable_ruby true
auto_typecast true
tag reformedhubbleCamelRouteJmx
<record>
value2 ${value.map { |k,v| '{"' + k.to_s + '": "Hello"}' }.join(",") }
</record>
</match>
<match reformedhubbleCamelRouteJmx>
type stdout
</match>

I'm not succeed to get something else than a string...

016-03-01 15:32:53 +0000 reformedhubbleCamelRouteJmx: {"foo":"bar","hello":"me","value":{"myobject":{"name":"object1"}},"value2":"{\"myobject\"=>\"Hello\"}"}

**Comment by sonots** [comment]
With your conf, I got like:

```
2016-03-02 01:32:52 +0900 reformedhubbleCamelRouteJmx: {"foo":"bar","hello":"me","value":{"myobject":{"name":"object1"}},"value2":"{\"myobject\": \"Hello\"}"}
2016-03-02 01:32:53 +0900 reformedhubbleCamelRouteJmx: {"foo":"bar","hello":"me","value":{"myobject":{"name":"object1"}},"value2":"{\"myobject\": \"Hello\"}"}
2016-03-02 01:32:54 +0900 reformedhubbleCamelRouteJmx: {"foo":"bar","hello":"me","value":{"myobject":{"name":"object1"}},"value2":"{\"myobject\": \"Hello\"}"}
```

Please paste corresponding conf and results. And, could you use markdown?

**Comment by pgodot** [comment]
Thanks Sonots, I will try to do it between meeting

**Comment by sonots** [comment]
Let me close. If you still have a problem, please reopen.
