### ISSUE TITLE
Placeholders overridden unexpectedly

### ISSUE THREAD

**Issue by kimamula** [sonots/fluent-plugin-record-reformer#40]
I found that placeholders are overridden if the same key appears in the input record.
Is this an expected behavior?

For example, if I change the below lines of test code

https://github.com/sonots/fluent-plugin-record-reformer/blob/master/test/test_out_record_reformer.rb#L28-L31

```ruby
record = {
  'eventType0' => 'bar',
  'message'    => msg,
}
```

to this,

```ruby
record = {
  'eventType0' => 'bar',
  'message'    => msg,
  'tag'        => 'foo' # add this line
}
```

many tests fail because ${tag} placeholder is now evaluated as `'foo'`.

From the document (https://github.com/sonots/fluent-plugin-record-reformer#placeholders), I expect ${tag} to be always replaced by the input tag.
If one want to use the value in the record which is keyed with 'tag', she should specify it by ${record["tag"]}.

**Comment by sonots** [comment]
Agree with you, not expected behavior
