### ISSUE TITLE
Removing time key

### ISSUE THREAD

**Issue by denizarman** [sonots/fluent-plugin-record-reformer#44]
Hi, i think there is a problem with removing "time" key, i dont know if it is mandatory or an issue, so please enlighten me.
When i check my logs with "docker logs", every fluentd message contains a time key as the last field of event. So i presume, fluentd adding time key. 
I am aware of record_transformer plugin has ability to remove keys with remove_keys parameter but at below sample it seems not working.

Below is my simplified fluentd config,

```
<source>
	type forward
	port 24224
</source>
<filter SomeTag.*>
  @type record_transformer
  enable_ruby true
  **remove_keys time** #this seems doesn't work
  <record>
	LogDate ${time.strftime('%Y/%m/%d %H:%M:%S')}
  </record>
</filter>
<match SomeTag.*>
	type copy
	<store>
		type elasticsearch
                ......
	</store>
	<store>
		type mongo
                ......
	</store>
	<store>
		type stdout
	</store>
</match>
```

Thanks for any help

**Comment by sonots** [comment]
this would have been fixed via https://github.com/sonots/fluent-plugin-record-reformer/pull/46
