### ISSUE TITLE
add field below another field

### ISSUE THREAD

**Issue by stevezau** [sonots/fluent-plugin-record-reformer#45]
Hi,

Is it possible to somehow create an additional field such as
```
<match foo.**>
  type record_reformer
  <record>
    _metadata <record>service bah</record>
    _metadata <record>something else</record>
  </record>
</match>
```

The event then will have a hash field _metadata??

{"_metadata": {"service": "bah", "something": "else"}}

**Comment by sonots** [comment]
nested field is not supported yet
