### ISSUE TITLE
Multiple tag match error

### ISSUE THREAD

**Issue by dshmatov** [sonots/fluent-plugin-record-reformer#50]
Fluentd: 0.14.23

I've got an issue with wildcard tag definition. When I point `*.team` tag this rewrite doesn't work. But when I point `some.team` tag instead of `*.team` tag it works.

```
<match *.team>
  @type rewrite_tag_filter
  <rule>
    key     team
    pattern (.*)
    tag     other.team
  </rule>
</match>
```

**Comment by sonots** [comment]
Please issue to rewrite_tag_filter. This repo is for record-reformer.
